better file checking

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -22,42 +22,44 @@ FORBIDDEN_FILES=(
     "terraform.tfvars"
 )
 
+DIFF_OUTPUT=$(git diff --cached --name-only)
+
 # Loop through all files that are staged for commit
-for FILE in $(git diff --cached --name-only); do
+for FILE in $DIFF_OUTPUT; do
     FILENAME=$(basename "$FILE")
-    # Check if the base filename (e.g., .env) is in our forbidden list
     for FORBIDDEN in "${FORBIDDEN_FILES[@]}"; do
         if [[ "$FILENAME" == "$FORBIDDEN" ]]; then
-            echo -e "\e[1;31mERROR: Detected potentially sensitive file in commit: '$FILE'\e[0m"
-            echo -e "\e[1;31mPlease remove it from staging before committing.\e[0m"
-            echo ""
-            echo "If this is intended, you can bypass the hook with 'git commit --no-verify'."
+            echo -e "ERROR: Detected potentially sensitive file in commit: '$FILE'"
+            echo -e "Please remove it from staging before committing."
+            echo -e "If this is intended, you can bypass the hook with 'git commit --no-verify'."
             exit 1 # Abort the commit
         fi
     done
 done
 
 # ---------------------------------------------------------------------------- #
-# pre-commit hook to run mypy for type checking and unittests
+# pre-commit hook to run mypy for type checking
 # ---------------------------------------------------------------------------- #
 
 MYPY_OUTPUT=$(.venv/bin/mypy --disallow-untyped-defs --disallow-incomplete-defs --disable-error-code=import-untyped app test > /dev/null 2>&1)
 MYPY_EXIT_CODE=$?
 
-UNITTEST_OUTPUT=$(.venv/bin/python -m unittest discover --failfast --verbose --start-directory ./test --pattern "*_test.py" > /dev/null 2>&1)
-UNITTEST_EXIT_CODE=$?
-
 if [ $MYPY_EXIT_CODE -ne 0 ]; then
 	echo -e "ERROR: Linting failed. Please fix the issues before committing."
-    echo ""
-    echo "If this is intended, you can bypass the hook with 'git commit --no-verify'."
+    echo -e "If this is intended, you can bypass the hook with 'git commit --no-verify'."
 	exit 1
 fi
 
+# ---------------------------------------------------------------------------- #
+# pre-commit hook to run unit tests
+# ---------------------------------------------------------------------------- #
+
+UNITTEST_OUTPUT=$(.venv/bin/python -m unittest discover --failfast --verbose --start-directory ./test --pattern "*_test.py" > /dev/null 2>&1)
+UNITTEST_EXIT_CODE=$?
+
 if [ $UNITTEST_EXIT_CODE -ne 0 ]; then
 	echo -e "ERROR: At least one unit test failed. Please fix the issues before committing."
-    echo ""
-    echo "If this is intended, you can bypass the hook with 'git commit --no-verify'."
+    echo -e "If this is intended, you can bypass the hook with 'git commit --no-verify'."
 	exit 1
 fi
 
